nginx:
  image: nginx
  container_name: nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - "/etc/nginx/conf.d"
    - "/etc/nginx/vhost.d"
    - "/usr/share/nginx/html"
    - "../.nginx/certs:/etc/nginx/certs:ro"
nginx-gen:
  image: jwilder/docker-gen
  container_name: nginx-gen
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock:ro"
    - "./template/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
  volumes_from:
    - nginx
  entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
letsencrypt-nginx-proxy-companion:
  image: jrcs/letsencrypt-nginx-proxy-companion
  container_name: letsencrypt-nginx-proxy-companion
  volumes_from:
    - nginx
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    - "../.nginx/certs:/etc/nginx/certs:rw"
  environment:
    - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
rancher:
  image: rancher/server
  container_name: rancher
  restart: always
  links:
    - db:db
  environment:
    VIRTUAL_HOST: rancher.dohrm.fr
    VIRTUAL_PORT: 8080
    LETSENCRYPT_HOST: rancher.dohrm.fr
    LETSENCRYPT_EMAIL: dohr.michael@gmail.com
    CATTLE_DB_CATTLE_MYSQL_HOST: db
    CATTLE_DB_CATTLE_MYSQL_PORT: 3306
    CATTLE_DB_CATTLE_MYSQL_NAME: rancher
    CATTLE_DB_CATTLE_USERNAME: rancher
    CATTLE_DB_CATTLE_PASSWORD: RancherPassword
mysql:
  image: mysql:5.7
  container_name: mysql
  volumes:
    - "../.data/db:/var/lib/mysql"
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: MyAwesomePassword
    MYSQL_DATABASE: rancher
    MYSQL_USER: rancher
    MYSQL_PASSWORD: RancherPassword
